pool:
  vmImage: 'ubuntu-latest'

trigger:
- master
- feature/rewrite

- task: Docker@2
  inputs:
    containerRegistry: 'airmapreg'
    repository: 'dss.grpcbackend'
    command: 'buildAndPush'
    Dockerfile: 'cmds/grpc-backend/Dockerfile'
    tags: '$(Build.SourceVersion)'

- task: Docker@2
  inputs:
    containerRegistry: 'airmapreg'
    repository: 'dss.httpgateway'
    command: 'buildAndPush'
    Dockerfile: 'cmds/http-gateway/Dockerfile'
    tags: '$(Build.SourceVersion)'

