- task: Docker@2
  inputs:
    containerRegistry: 'airmapreg'
    repository: 'dss.httpgateway'
    command: 'buildAndPush'
    Dockerfile: 'cmds/http-gatewat/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'airmapreg'
    repository: 'dss.grpcbackend'
    command: 'buildAndPush'
    Dockerfile: 'cmds/grpc-backend/Dockerfile'